version: "3"
services:
  compression:
    build: ./service-1
    ports:
      - 8081:8081
      - 8001:8001
    environment:
      COMPRESSION_HOST: compression
      UPLOAD_HOST: upload
      CRUD_HOST: crud
  upload:
    build: ./service-2
    ports:
      - 8082:8082
      - 8002:8002
    environment:
      COMPRESSION_HOST: compression
      UPLOAD_HOST: upload
      CRUD_HOST: crud
  crud:
    build: ./service-3
    ports:
      - 8082:8083
      - 8002:8003
    environment:
      COMPRESSION_HOST: compression
      CRUD_HOST: crud
